---
title: 'Homework #5'
author: "Bayesian Psychometric Modeling (PSQF 7375, Fall 2024)"
date: "Due Friday, December 13th, 2024 at 11:59pm in ICON"
output: word_document
---

## Bayesian Psychometric Models

The objectives of this homework are:

1. To learn how to estimate a multidimensional polytomous item response model with MCMC
2. To see how each type of observed data assumption impacts the latent variable estimates
3. To learn how to assess absolute and relative model fit

### General Instructions:

The data for homework 5 were collected at a casino from a sample of persons who were gambling. The content and response options for 24 items measuring pathological gambling are given in the excel file GRI_Items.xlsx, along with the item responses in the excel file GRI_Data.xlsx. Use Stan for all models in this assignment. 

Also in the GRI_Items.xlsx file are two columns that provide the entries for the Q-matrix to use (titled Financial and Non-Financial). Please use this Q-matrix in your multidimensional analysis.

#### For all questions below, when estimates are requested, report:

* The posterior mean (EAP) 
* The posterior standard deviation 
* The 95% highest density posterior interval (lower and upper bound)

#### To estimate each model, use Stan with the following options: 

* Four chains
* Warmup of 5000 iterations
* Sampling of 5000 iterations
* Starting values drawn from $N(10,1)$ for all factor loading/discrimination parameters 

You may work with other students in building the homework, but your answers and syntax must not be copied from anyone else.

### Submission Instructions:

Please submit your homework as an R Markdown file where all R syntax is embedded as chunks and each answer is provided using your words (text answers are required, not just output) following each question in the section marked **My Answer**. 

**Name your file with your first and last name and submit your file to ICON.**

### Data File

The data file is available for download at [https://jonathantemplin.com/wp-content/uploads/2022/11/GRI_Data.xlsx](https://jonathantemplin.com/wp-content/uploads/2022/11/GRI_Data.xlsx). The list of items are available at [https://jonathantemplin.com/wp-content/uploads/2022/11/GRI_Items.xlsx](https://jonathantemplin.com/wp-content/uploads/2022/11/GRI_Items.xlsx)

The variables in the data are:

* ID: The ID number of the person
* gri1-gri24: The response to a 6-point Likert item for each person

The purpose of this homework is for you to practice multidimensional polytomous item response models (the graded response model), including writing the syntax for the model, as well as finding and and interpreting the relevant pieces of output. The graded response model assumes each observed item follows a conditional multinomial (categorical) distribution with a logistic link function and a proportional odds assumption and each factor follows a normal distribution. 

Model 1: Using Stan, estimate a single-factor graded response model for all items. Use the z-score method of identification, in which the factor mean is fixed to 0, the factor variance is fixed to 1, and all item parameters are estimated. 

Model 2: Using Stan, estimate a two-factor graded response model for all items using the Q-matrix in GRI_Items.xlsx. Use the z-score method of identification, in which each factor mean is fixed to 0, each factor variance is fixed to 1, and all factor correlations are estimated.

Model 3: Using Stan, reestimate model 2 but with empirical priors on the factor loadings and on the item intercept parameters. Use the z-score method of identification, in which each factor mean is fixed to 0, each factor variance is fixed to 1, and all factor correlations are estimated. For the empirical priors, estimate one mean and standard deviation for the loading/discrimination parameters and one mean and one standard deviation for the item intercept parameters.

Model 4: Using Stan, reestimate model 2 but with marker items where the first factor loadings for each dimension is set to one. For scale identification, set each factor mean to 0, but estimate each factor variance and all factor correlations.

Finally, include syntax within Stan to assess absolute and relative model fit for each model. For absolute fit, use the posterior predictive p-value (ppp) for Pearson correlations. For relative fit, use the Widely Applicable Information Criterion (WAIC) and LOO-PSIS (Leave One Out-Pareto Smoothed Importance Sampling).

Answer the following questions for Model 2 (Model 1 was a previous homework):

**1. What is the model for each observed item response (i.e., the linear predictor, the link function, the submodels, the distribution, and any other parameters) **

**My Answer**

**2. Did your Markov chains converge? What evidence do you have to support your answer?**

**My Answer**

**3. What are your estimates for each item intercept parameter?** (see estimate details above for what to report)

**My Answer**

**4. What are your estimates for each factor loading/discrimination parameter** (see estimate details above for what to report)

**My Answer**

**5. What are your estimates for the factor scores?** (see estimate details above for what to report)

**My Answer**

**6. What are your estimates for the factor correlation?** (see estimate details above for what to report)

**My Answer**

***7. What are your estimates for the factor variance?** (see estimate details above for what to report)

**My Answer**

**8. Which items had posterior predictive p-values for their Pearson correlations that were less than 0.05 or greater than 0.95?**

**My Answer**

**9. What are the WAIC and LOO-PSIS values for this model?**

**My Answer**

**10. Which model (model 1 or 2) is preferred based on WAIC and LOO-PSIS?**

**My Answer**

<!-- Here, make a set of questions for model 3  -->

Answer the following questions for Model 3:

**11. Did your Markov chains converge? What evidence do you have to support your answer?**

**My Answer**

**12. What are your estimates for each item intercept parameter?** (see estimate details above for what to report)

**My Answer**

**13. What are your estimates for each factor loading/discrimination parameter** (see estimate details above for what to report)

**My Answer**

**14. What are your estimates for the factor scores?** (see estimate details above for what to report)

**My Answer**

**15. What are your estimates for the factor correlation?** (see estimate details above for what to report)

**My Answer**

**16. Which items had posterior predictive p-values for their Pearson correlations that were less than 0.05 or greater than 0.95?**

**My Answer**

**17. What are the WAIC and LOO-PSIS values for this model?**

**My Answer**

**18. Which model (model 2 or 3) is preferred based on WAIC and LOO-PSIS?**

**My Answer**

<!-- Now make a set of questions comparing model 3 to model 2 -->

**19. Create a scatterplot of the factor scores for the model 3 compared to model 2. What do you observe?**

**My Answer**

**20. Create a scatterplot of the factor loadings for model 3 compared to model 2. What do you observe?**

**My Answer**

**21. Create a scatter plot of the item intercepts for model 3 compared to model 2. What do you observe?**

**My Answer**

<!-- Now make a set of questions for model 4 -->

Answer the following questions for Model 4:

**22. Did your Markov chains converge? What evidence do you have to support your answer?**

**My Answer**

**23. What are your estimates for each item intercept parameter?** (see estimate details above for what to report)

**My Answer**

**24. What are your estimates for each factor loading/discrimination parameter** (see estimate details above for what to report)

**My Answer**

**25. What are your estimates for the factor scores?** (see estimate details above for what to report)

**My Answer**

**26. What are your estimates for the factor correlation?** (see estimate details above for what to report)

**My Answer**

**27. Which items had posterior predictive p-values for their Pearson correlations that were less than 0.05 or greater than 0.95?**

**My Answer**

**28. What are the WAIC and LOO-PSIS values for this model?**

**My Answer**

**29. Which model (model 2, 3, or 4) is preferred based on WAIC and LOO-PSIS?**

**My Answer**

**30. Create a scatterplot of the factor scores for the model 4 compared to model 2. What do you observe?**

**My Answer**

**31. Create a scatterplot of the factor loadings for model 4 compared to model 2. What do you observe?**

**My Answer**

**32. Create a scatter plot of the item intercepts for model 4 compared to model 2. What do you observe?**

**My Answer** 





